
@startuml
title: Distributed crate with links to object crates
package "name My Corpus" as mc {
   rectangle "@type: [Dataset, RepositoryCollection]\nconformsTo: ./#Collection" as cc {

   }
}

package "ROCrate: Collection A" as cAc {

   rectangle "@type:  [Dataset, RepositoryCollection]\nconformsTo: ./#Collection" as ca {

   }
  
}


package "ROCrate: Collection B" as cBc {

   rectangle "@type:  [Dataset, RepositoryCollection]\nconformsTo: ./#Collection" as cb {

   }
  
}


package "RO Crate: Interview #1" as ec2 {
  rectangle "@type: RepositoryObject\nconformsTo: ./#Object\ncommuncationMode: SpokenLanguge\nlingusiticGenre: Interview" as eo1 {

   }
   
 rectangle "File: files/audio1.wav\nmaterialType: PrimaryMaterial\ncommunicationMode: SpokenLanguage" as ea1
   rectangle "File: files/csv1.csv\nmaterialType: Annotation" as ecsv1
    
   
   
      }



eo1 -down-> ea1 : hasPart
eo1 -down-> ecsv1 : hasPart

eo1 -up-> ca : memberOf
ca -up-> cc : memberOf
cb -up-> cc : memberOf

note right of cc : Repository Collection:\n- MUST contain descriptive metadata\n  for the corpus/collection\n- MAY contain hasMember relationships\n  listing child Collections or Objects

 
note bottom of ec2 : Individual object with file data

@enduml
