
@startuml
title: Structure of an Object crate


actor "Speaker 1" as s1
actor "Speaker 2" as s2

rectangle "RO-Crate Profile" {
rectangle "#Collection" as procoll
rectangle "#Object" as proobj
}

rectangle "Conversation" as c1 {

 
 rectangle "@type: [RepositoryObject]" 

}
rectangle "Audio File" as audio1 {
   rectangle "@id: [file.wav]\n@type: [File, PrimaryMaterial]\ncommunicationsMode: [SpokenLanguage]\ncommunicationGenre: [Interview]\nresourceType: [PrimaryMaterial]\nencodingFormat: [audio/x-wav]" 


}
rectangle "PDF File" as pdf1 {
   rectangle "@id: [file.pdf]\n@type: [File, Annotation]\nannotationType: [Transcription]\ncommunicationMode: [WrittenLanguage]\nresourceType: [DerivedMaterial]\nencodingFormat: [Material/pdf]" as pt 

}

rectangle "CSV File" as csv1 {
   rectangle "@id: [file.csv]\n@type: [File, Annotation, DerivedMaterial]\nannotationType: [Transcription]\ncommunicationMode: [WrittenLanguage]\nresourceType: [DerivedMaterial]\nencodingFormat: [text/csv]" 
}

c1 -down-> pdf1 : hasPart

pdf1 -up-> audio1 : annotationOf
c1 -down-> audio1 : hasPart
c1 -down-> csv1 : hasPart
csv1 -up-> audio1 : annotationOf
csv1 -up-> pdf1 : derivedFrom

c1 -left-> s1 : interviewer
c1 -right-> s2 : interviewee
c1 ->  proobj: conformsTo


@enduml
